### ISSUE TITLE
Group assertions in WFS 1.0 test to better distinguish the mandatory and optional test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs10#1]
The test suite contains all WFS 1.0 tests inlcuding Class C, which are \""An
optional, testable assertion.\"
http://cite.opengeospatial.org/teamengine/wfs-1.0.0/index.html
The test should be updated so it clearly reports that an implementation has
paased the Mandatory tests or Mandatory+Optional.
[Originally reported in the OGC CITE issue tracker: issue #854](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=854)  

_Opened: 2013-08-14 14:11:44 Last Updated: 2013-10-31 10:02:49_

**Comment by dstenger** [comment]
Content of the enhancement should be moved to the wiki.

**Comment by dstenger** [comment]
Content of the enhancement was moved to the wiki: https://github.com/opengeospatial/ets-wfs10/wiki/Group-assertions-in-WFS-1.0-test-to-better-distinguish-the-mandatory-and-optional-test
