### ISSUE TITLE
 Introduce Dockerfile and Maven Docker plugin

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs10#19]
Please see: [How to create Docker Images of test suites](https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites)

**Comment by lgoltz** [comment]
Test report is not shown:
```
98558a> java.lang.ClassNotFoundException: org/apache/xerces/jaxp/DocumentBuilderFactoryImpl
98558a> 	at java.lang.Class.forName0(Native Method)
98558a> 	at java.lang.Class.forName(Class.java:348)
98558a> 	at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
98558a> 	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
98558a> 	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
98558a> 	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
```

**Comment by keshav-nangare** [comment]
@lgoltz @dstenger 

According to exception maybe the corresponding Jar is missing.  I did some workaround listed the jars from `webapp/teamengine/WEB-INF/lib` the `xercesImpl` jar is present still it throwing the above errors.

**Comment by lgoltz** [comment]
Dependency org.opengis.cite.cite1-utils:1.1.1 should be removed (or replaced by org.opengis.cite.schema-utils:1.8).

**Comment by keshav-nangare** [comment]
I have pushed changes into the same branch with commit [`fa00e38`](https://github.com/opengeospatial/ets-wfs10/pull/24/commits/fa00e3895df63b9127a81244a05b75d36c62c0a6)
