### ISSUE TITLE
Description of tests mixes GET and POST

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs10#27]
Following section https://cite.opengeospatial.org/te2/about/wfs/1.0.0/site/testreq.html#getCapabilitiesPost--%20GetCapabilities%20over%20HTTP%20POST%20Tests has HTTP GET in description although HTTP POST requests are described.

The complete document shall be checked if GET and POST are used correctly in all test descriptions.

**Comment by keshav-nangare** [comment]
@dstenger 

I can see the same problem in the assertion of tests. Should I update the assertions of tests?

**Comment by dstenger** [comment]
Yes, please update those as well.

**Comment by keshav-nangare** [comment]
I have updated the description in documentation as well as comments in the test file with this #28 PR.
