### ISSUE TITLE
gml:description and gml:name must be optional

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs10#3]
Some tests expect GML response with gml:description and gml:name. Which according to schema is not necessary ( optional elements, minOccurs =0). Some implementations fail because they do not return these optional elements.

Test wfs:test1.0.0-basic-getfeature-get-9 
Test wfs:test1.0.0-basic-getfeature-post-9

**Comment by segoerke** [comment]
Imho this belongs to the underlying test data which contain these elements. I think the purpose of these tests is, to check if the specifics of the test data (which are GML things) can be handled correctly by an implementation

**Comment by bermud** [comment]
@segoerke, we should not fail an implementation if it is not providing optional elements. Can you please fix the underlying test data?

**Comment by dstenger** [comment]
Can you provide us a test URL we can use to reproduce this bug?

**Comment by dstenger** [comment]
We checked the test data [1] and they contain values for the elements gml:description and gml:name. So, a service passes the test, if it uses the provided test data.

Of course, we could update the test, but as the test suite is data agnostic this test should not fail, if all test data are provided by the service.
As all tests of this test suite are data agnostic, we would rather propose that the provider of the service checks if all test data have been imported correctly.

[1] ​https://github.com/opengeospatial/ets-wfs10/blob/master/src/site/resources/data/data-wfs-1.0.0.zip

**Comment by bermud** [comment]
@dstenger. I'm opening this issue again. The data should follow the specification requirements and should not add tests that are not mandatory. Please update the test data and ctls as needed.

**Comment by dstenger** [comment]
A fix was created for this issue.

Fix is part of following pull request #7 and will be part of the next release.

**Comment by dstenger** [comment]
Pull request was merged successfully into master branch and is part of the upcoming release.
