### ISSUE TITLE
test data link is broken in site

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs10#5]
http://cite.opengeospatial.org/teamengine/about/wfs/1.0.0/site/ in 1.8

**Comment by dstenger** [comment]
The test data should be located in following directory: te_base/scripts/wfs/1.0.0/site/data/

Can you please check if the link is set correctly (the link should not go to the resources folder but to the directory mentioned above)?

**Comment by dstenger** [comment]
The test data should be located in following directory: te_base/scripts/wfs/1.0.0/site/data/

Can you please check if the link is set correctly (the link should not go to the resources folder but to the directory mentioned above)?

**Comment by dstenger** [comment]
Similar issue: https://github.com/opengeospatial/ets-wms11/issues/35

**Comment by dstenger** [comment]
I tested the fix on our test environment and it works.

The pull request will be merged, when the next release is prepared.

**Comment by dstenger** [comment]
Pull request was merged to master branch. This fix will be part of the next release.
