### ISSUE TITLE
xs:dateTime at basic-getfeature-get-9, basic-getfeature-post-9

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs10#8]
Should the test be change to support also xs:dateTime?  It seems the test only supports xs:date.

**Comment by dstenger** [comment]
No, just xs:date is supported for FeatureType cdf:Other (used in basic-getfeature-get-9 and basic-getfeature-post-9).

This is defined in the schema for the test data: https://github.com/opengeospatial/cite1-utils/blob/master/src/main/resources/schemas/dataFeatures.xsd

**Comment by bermud** [comment]
If organizations fail these tests because of the test data, we should grant an exception.
Test wfs:test1.0.0-basic-getfeature-get-9: Failed
Test wfs:test1.0.0-basic-getfeature-post-9: Failed
