### ISSUE TITLE
No Rest API

### ISSUE THREAD

**Issue by pblottiere** [opengeospatial/ets-wfs10#9]
Hi,

I would like to run ets-wfs10 tests thanks to the Rest API as I'm doing it with ets-wms13, ets-gml32 or ets-wfs20 but it does not seem to be available on the page http://localhost:8080/teamengine/rest/suites/.

I have installed/unarchived the next packages after the compilation step:

- ets-wfs10-1.11-deps.zip in $(TE_BASE)/resources/lib
- ets-wfs10-1.11-ctl.zip in $(TE_BASE)/scripts

Versions currently used:

    teamengine: 4.10
    ets-wfs10: 1.11
    Ubuntu 16.04.1 LTS

Am I missing something?

Thank you for your work!

**Comment by lgoltz** [comment]
As far as I understand from https://github.com/opengeospatial/teamengine/issues/190 the REST API works with TestNG suites but not with CTL Suites (as the ets-wfs10). The extension provides support of REST for CTL Suites in general, but the implementation of a CtlControllers in specific test suites is still required.

**Comment by dstenger** [comment]
REST API was enabled is provided via pull request #15.

Example which can be used to address REST interface: http://host/teamengine/rest/suites/wfs/1.12-SNAPSHOT/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs100?service=WFS%26request=GetCapabilities

If fix https://github.com/opengeospatial/teamengine/issues/219 is enabled in TEAM Engine installation, an EARL report is returned when following request header is set: ```Accept:application/rdf+xml```

EARL response is currently limited as #10 has to be solved for a complete report.
